version: '3.3'
services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ['yarn', 'run', 'start:dev']
    ports:
      - '4000:4000'
    networks:
      - your-network
    depends_on:
      - database
      - redis
    volumes:
      - .:/app

  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env
    networks:
      - your-network
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - your-network
    volumes:
      - redis-data:/data
    command: >
      --requirepass ${REDIS_PASSWORD}

networks:
  your-network:

volumes:
  mongodb-data:
  redis-data:
