version: '3.3'
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["yarn", "run", "start:dev"]
    ports:
      - '4000:4000'
    networks:
      - your-network
    depends_on:
      - database
    volumes:
      - .:/app

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env
    networks:
      - your-network
    volumes:
      - mongodb-data:/data/db

networks:
  your-network:

volumes:
  mongodb-data:
